<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $settings = [
            [
                'name'=>'app_name',
                'val'=>'Crecer Contigo',
                'type'=>'string'
            ],
            [
                'name'=>'logo',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'favicon',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'logo_white',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'logo_secondary',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'logo_third',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'watermark',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'banner_default',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'subtitle',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'description',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'mail_driver',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'mail_host',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'mail_port',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'mail_username',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'mail_password',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'mail_encryption',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'mail_from_address',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'mail_from_name',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'google_map_api_key',
                'val'=>'AIzaSyDTBlJlxGxQy08zj9zvTHYmOd84Y5ydv5U',
                'type'=>'string'
            ],
            [
                'name'=>'facebook_app_id',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'facebook_app_secret',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'google_app_id',
                'val'=>'',
                'type'=>'string'
            ],
            [
                'name'=>'google_app_secret',
                'val'=>'',
                'type'=>'string'
            ]
        ];
        \App\Models\Setting::insert($settings);
    }
}
